### ISSUE TITLE
Request: add Wheel built on Linux in PyPI

### ISSUE THREAD

**Issue by hangyao** [yuangu/sxtwl_cpp#6]
So it can be pip installed on AWS Lambda environment.

Thanks!

**Comment by yuangu** [comment]
Because   little of   Windows users  to install C++ environment. It's necessary to build wheels for them. Now, I know it's also necessary to Linux User.Next I'll write Linux scripts for build it. Would you please test it for me then?   Here is  build wheel of Windows automated scripts:https://github.com/yuangu/sxtwl_cpp_python_builder

**Comment by hangyao** [comment]
Sure I can do the testing.

Thanks!

**Comment by StuckInLoop** [comment]
any information on making it work under Linux?

**Comment by yuangu** [comment]
已经提供了linux的wheel包,接口也更新了
